### ISSUE TITLE
ImportError: cannot import name 'LooseVariableGetterBlock' from 'TagScriptEngine'

### ISSUE THREAD

**Issue by calvinthefreak** [phenom4n4n/phen-cogs#111]
Error while installing roleutils
```
Language           │ en-US
Red version        │ 3.4.14  
Discord.py version │ 1.7.3   
Storage type       │ Postgres

Python 3.8.10
```

This Setup of redbot is inside an ubuntu-docker-container.
it seems like, that the "TagScriptEngine" is not correctly installed. And yes, I know, to run red as ROOT is bad. That is a historical thing, I cant change it right now.

```py
[2021-12-20 17:14:11] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/root/redenv/lib/python3.9/site-packages/redbot/core/core_commands.py", line 176, in _load
    await bot.load_extension(spec)
  File "/root/redenv/lib/python3.9/site-packages/redbot/core/bot.py", line 1510, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/.local/share/Red-DiscordBot/data/AmadeusKurisu/cogs/CogManager/cogs/roleutils/__init__.py", line 30, in <module>
    from .roleutils import RoleUtils
  File "/root/.local/share/Red-DiscordBot/data/AmadeusKurisu/cogs/CogManager/cogs/roleutils/roleutils.py", line 35, in <module>
    from .roles import Roles
  File "/root/.local/share/Red-DiscordBot/data/AmadeusKurisu/cogs/CogManager/cogs/roleutils/roles.py", line 35, in <module>
    from TagScriptEngine import Interpreter, LooseVariableGetterBlock, MemberAdapter
ImportError: cannot import name 'LooseVariableGetterBlock' from 'TagScriptEngine' (/root/redenv/lib/python3.9/site-packages/TagScriptEngine/__init__.py)
```

**Comment by phenom4n4n** [comment]
Hello, this seems to be an issue with your TagScript installation. Please go to *#support_phen-cogs* on the [cog support server](https://discord.gg/GET4DVk) for further instructions.
