### ISSUE TITLE
[LinkQuoter] Quotes not working

### ISSUE THREAD

**Issue by DJTOMATO** [phenom4n4n/phen-cogs#176]
```py
[2023-07-27 19:31:04] [ERROR] discord.client: Ignoring exception in on_message_without_command
Traceback (most recent call last):
  File "/home/glas/redenv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/linkquoter/linkquoter.py", line 392, in on_message_without_command
    quoted_message = await LinkToMessage().convert(ctx, message.content)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/linkquoter/converters.py", line 53, in convert
    return await self.validate_message(ctx, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/linkquoter/converters.py", line 83, in validate_message
    if message.channel.is_nsfw() and not ctx.channel.is_nsfw():
       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PartialMessageable' object has no attribute 'is_nsfw'
```

**Comment by japandotorg** [comment]
I don’t think it has something to do with the cog, looks like dpy is returning the channel as a `PartialMessageable` which usually happens when the channel is not in the bot’s cache.
I cannot seem to reproduce error either

**Comment by DJTOMATO** [comment]
Yeah you're right, after furter testing it happens with an specific text message, any message after of before works fine. I guess there was an hiccup or something?
