### ISSUE TITLE
[PermissionsLocker] Embed sending on permlock cmd

### ISSUE THREAD

**Issue by aikaterna** [phenom4n4n/phen-cogs#24]
Bot didn't have send embed perms. Not sure how you'd like to handle it since there's a couple different approaches, so I'm opening an issue.

```
Traceback (most recent call last):
  File "/.../cat38/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/.../Red-DiscordBot/cogs/CogManager/cogs/permissionslocker/permissionslocker.py", line 96, in permlock
    await ctx.send(embed=e)
  File "/.../cat38/lib/python3.8/site-packages/redbot/core/commands/context.py", line 93, in send
    return await super().send(content=content, **kwargs)
  File "/.../cat38/lib/python3.8/site-packages/discord/abc.py", line 904, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/.../cat38/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../cat38/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/.../cat38/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 814, in invoke
    await super().invoke(ctx)
  File "/.../cat38/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1325, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/.../cat38/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

**Comment by phenom4n4n** [comment]
Resolved in the latest commit with the addition of the `[p]permlock settings` command which requires embed perms.
