### ISSUE TITLE
aki session sometimes ends with json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by siu3334** [phenom4n4n/phen-cogs#28]
Hi,

aki session sometimes ends with said error as title says:
Here is the full traceback:
```py
Traceback (most recent call last):

  File "/opt/lib/python3.9/site-packages/redbot/vendored/discord/ext/menus/__init__.py", line 638, in update
    await button(self, payload)
  File "/opt/cogs/CogManager/cogs/aki/aki.py", line 34, in no
    await self.aki.answer("no")
  File "/opt/lib/python3.9/site-packages/akinator/async_aki/async_akinator.py", line 189, in answer
    resp = self._parse_response(await w.text())
  File "/opt/lib/python3.9/site-packages/akinator/async_aki/async_akinator.py", line 88, in _parse_response
    return json.loads(",".join(response.split("(")[1::])[:-1])
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I have a feeling this is an issue with upstream library but unsure so here's an issue.

**Comment by phenom4n4n** [comment]
This is an issue with the akinator library that I'm not sure will be fixed. I've pushed a catch for it that will explain the game errored out.
