### ISSUE TITLE
[CustomPing] Host latency broken

### ISSUE THREAD

**Issue by Technetium1** [phenom4n4n/phen-cogs#39]
![image](https://user-images.githubusercontent.com/9877150/114107939-f6a28480-989f-11eb-80d8-ba0a8209d159.png)
Traceback:
```py
Traceback (most recent call last):
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/red/.local/share/Red-DiscordBot/data/TechBot/cogs/CogManager/cogs/customping/customping.py", line 111, in ping
    s = speedtest.Speedtest(secure=True)
  File "/home/red/.local/share/Red-DiscordBot/data/TechBot/cogs/Downloader/lib/speedtest.py", line 1091, in __init__
    self.get_config()
  File "/home/red/.local/share/Red-DiscordBot/data/TechBot/cogs/Downloader/lib/speedtest.py", line 1173, in get_config
    ignore_servers = list(
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1353, in invoke
    await super().invoke(ctx)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: invalid literal for int() with base 10: ''
```

**Comment by phenom4n4n** [comment]
The underlying issue here is with the `speedtest` lib which pushed a fix for this recently. You can update to the latest version with `[p]pipinstall speedtest-cli`. Additionally, the cog has been edited to catch any exceptions and have a cleaner output when fetching host latency.
