### ISSUE TITLE
[DisboardReminder] Update failed

### ISSUE THREAD

**Issue by Technetium1** [phenom4n4n/phen-cogs#42]
rapidfuzz seems to not be in the requirements but it was added in https://github.com/phenom4n4n/phen-cogs/commit/5bf081e125831e288855442af7a76977ce971017
Traceback:
```py
Exception during loading of package
Traceback (most recent call last):
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/redbot/core/core_commands.py", line 171, in _load
    await bot.load_extension(spec)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/redbot/core/bot.py", line 1355, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/red/.local/share/Red-DiscordBot/data/TechBot/cogs/CogManager/cogs/disboardreminder/__init__.py", line 25, in <module>
    from .disboardreminder import DisboardReminder
  File "/home/red/.local/share/Red-DiscordBot/data/TechBot/cogs/CogManager/cogs/disboardreminder/disboardreminder.py", line 45, in <module>
    from .converters import FuzzyRole, StrictRole
  File "/home/red/.local/share/Red-DiscordBot/data/TechBot/cogs/CogManager/cogs/disboardreminder/converters.py", line 4, in <module>
    from rapidfuzz import process
ModuleNotFoundError: No module named 'rapidfuzz'

```

**Comment by phenom4n4n** [comment]
Thanks for reporting this, it's been fixed now.
