### ISSUE TITLE
[Tags] Problems loading

### ISSUE THREAD

**Issue by kyle95wm** [phenom4n4n/phen-cogs#76]
I keep getting this error:

```Exception during loading of package
Traceback (most recent call last):
  File "/home/bot/redenv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 171, in _load
    await bot.load_extension(spec)
  File "/home/bot/redenv/lib/python3.8/site-packages/redbot/core/bot.py", line 1364, in load_extension
    lib.setup(self)
  File "/home/bot/.local/share/Red-DiscordBot/data/proleman/cogs/CogManager/cogs/tags/__init__.py", line 44, in setup
    bot.add_cog(Tags(bot))
  File "/home/bot/.local/share/Red-DiscordBot/data/proleman/cogs/CogManager/cogs/tags/core.py", line 90, in __init__
    bot.add_dev_env_value("tags", lambda ctx: self)
  File "/home/bot/redenv/lib/python3.8/site-packages/redbot/core/bot.py", line 352, in add_dev_env_value
    raise RuntimeError(f"The name {name} is already used.")
RuntimeError: The name tags is already used.```

This happens every time I try to load the cog.

**Comment by phenom4n4n** [comment]
Hey, thanks for reporting this issue. Can you go to my support channel on the cog support server so I can ask for more context?
