### ISSUE TITLE
tags: access bot instance in Custom Block environment

### ISSUE THREAD

**Issue by synrg** [phenom4n4n/phen-cogs#84]
I'd like to be able to access the bot instance in the Custom Block environment so that I can write code like:

[p]tagset block add taxon
```py
from functools import partial
from pyinaturalist import get_taxa_autocomplete

bot = self.bot  # self is the cog (i hope!)

class TaxonName(tse.Block):
    ACCEPTED_NAMES = ("taxon",)

    async def process(self, ctx: tse.Context):
        query = ctx.verb.payload
        response = await bot.run_in_executor(None, partial(get_taxa_autocomplete, q=query))
        if response:
            results = response.get("results")
            if results:
                taxon = results[0]
                return taxon["name"]
        return "No Match"

return TaxonName
```

Unfortunately, that results in:

```py
Traceback (most recent call last):
  File "/home/synrg/.local/share/Red-DiscordBot/data/CuckooBee/cogs/CogManager/cogs/tags/owner.py", line 111, in tagsettings_block_add
    block = self.compile_block(code)
  File "/home/synrg/.local/share/Red-DiscordBot/data/CuckooBee/cogs/CogManager/cogs/tags/owner.py", line 61, in compile_block
    result = env["func"]()
  File "<string>", line 6, in func
NameError: name 'self' is not defined
```

My workaround is to use `loop = asyncio.get_event_loop()` and then run the synchronous API call `get_taxa_autocomplete` in that, and that works, but being able to use the bot instance would open up other possibilities for custom blocks for which there are no such convenient alternatives.

**Comment by phenom4n4n** [comment]
You can now use bot to access the bot object or tags to access the tags cog as global variables.
